### ISSUE TITLE
Newbie question;

### ISSUE THREAD

**Issue by Paulie420** [klu-dev/socks5-tunnel#1]
Hello, I found your repo when searching for sock5-tunnel info for Windows 11... 

Why would one need this application as opposed to using;
ssh -D 8080 homenetwork.com

?? - I'm appreciative of your work and am honestly asking to be educated, not difficult. 📦 
Thanks, Klu-dev.

**Comment by klu-dev** [comment]
Hi, thanks for your comments. I think there are following difference compared with SSH:
1. It's simple. Only copy binary and run it.
2. It support http proxy. Windows proxy setting use http proxy. User can switch on/off windows proxy easily to control web application access through proxy. No need to configure proxy for every browser. SSH only support socks5
3.  It supports simple router function to configure IP address segment to bypass proxy.
4. In future, the tunnel will use UDP (quick) protocol instead of TCP to provide better performance.
